import os
import re
import numpy as np
import tkinter as tk
import matplotlib.pyplot as plt
from collections import defaultdict
from matplotlib.ticker import FuncFormatter


def start_LaTeX(output_data):
    for group in output_data:
        for file_path in group["files"]:
            # Extract the filename
            file_name = os.path.basename(file_path)
            parent_folder = os.path.dirname(os.path.dirname(file_path))
            # Get the first part of the filename before the first underscore
            base_name = file_name.split('_')[2]

    LATEX_FILE = os.path.join(parent_folder, f"LaTeX_output_{base_name}_EN.txt")  # Save output as a TXT file
    """Initializes the LaTeX file if it does not exist yet."""
    with open(LATEX_FILE, "w") as latex_file:
        latex_file.write("\\documentclass{article}\n")
        latex_file.write("\\usepackage{amsmath}\n")
        latex_file.write("\\usepackage{graphicx}\n")
        latex_file.write("\\usepackage[utf8]{inputenc}\n")
        latex_file.write("\\usepackage{multirow}\n")
        latex_file.write("\\usepackage{longtable}\n")  # Support for multi-page tables
        latex_file.write("\\usepackage{booktabs}\n")   # Better tables
        latex_file.write("\\usepackage{array}\n")      # Better cell formatting
        latex_file.write("\\begin{document}\n\n")
        latex_file.write(f"\\title{{Evaluated measurements for membrane: {base_name}}}\n")
        latex_file.write("\\author{Automated export}\n")
        latex_file.write("\\date{}\n")
        latex_file.write("\\maketitle\n\n")
        latex_file.write("This file is a summary of measurement results, and everything contained is generated by a Python program.\\ \n")
        latex_file.write("\\\ \n")
    print("LaTeX file initialized: latex_output.txt")
    return LATEX_FILE


def end_LaTeX(LATEX_FILE):
    """Closes the LaTeX file and makes it ready for later PDF compilation."""
    with open(LATEX_FILE, "a") as latex_file:
        latex_file.write("\\end{document}\n")
    print("Document closed. LaTeX file ready for compilation.")


def format(latex_file_path):
    """Finds and replaces all occurrences of 'x.yye±z' with LaTeX notation '$x.yy \\times 10^{±z}$' and replaces $$ with $."""
    
    with open(latex_file_path, "r") as file:
        content = file.read()
    
    # Regular expression to find numbers in the format 'x.yy e±z' (e.g., '5.90e-6')
    pattern = r'(\d+\.\d+)e(-?\d+)'

    # Replacement function for LaTeX formatting
    def replacement(match):
        base = match.group(1)  # Number (e.g., "5.90")
        exponent = str(int(match.group(2)))  # Exponent as an integer (removes leading zeros)
        return f"${base} \\times 10^{{{exponent}}}$"  # Correct LaTeX notation with dollar signs

    formatted_content = re.sub(pattern, replacement, content)

    # Replace $$ with $
    formatted_content = formatted_content.replace("$$", "$")

    with open(latex_file_path, "w") as file:
        file.write(formatted_content)


def export_LaTeX_1(output_data, LATEX_FILE):
    """Adds two tables, correctly separated, to an existing LaTeX TXT file."""

    with open(LATEX_FILE, "a") as latex_file:
        # Section with tables
        latex_file.write("\\section*{Table 2: Basic measurement parameters}\n")
        latex_file.write("\\vspace{5mm}\n")
        latex_file.write("\\setlength{\LTleft}{-2.5cm} \n")
        latex_file.write("\\begin{longtable}{|c|c|c||c|c|c||c|} \n")
        latex_file.write("\\hline \n")
        latex_file.write("C. density & \multirow{2}{*}{Meas.} & Duration of meas. & Max. Pressure & Consumption & Pressure Time & Equilibrium Time \\\ (A/cm$^{2}$) &  & (h) & (bar) & (kWh/kg) & (h) & (h) \\\\\n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endfirsthead \n")
        latex_file.write("\\hline \n")
        latex_file.write("C. density & \multirow{2}{*}{Meas.} & Duration of meas. & Max. Pressure & Consumption & Pressure Time & Equilibrium Time \\\ (A/cm$^{2}$) &  & (h) & (bar) & (kWh/kg) & (h) & (h) \\\\\n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endhead \n")

        for group in output_data:
            x_value = group["x_value"]
            files = group["files"]
            num_files = len(files)

            latex_file.write("\\hline \n")

            for idx, file in enumerate(files):
                max_pressure = -float('inf')
                max_pressure_time = None
                max_pressure_1 = -float('inf')
                max_work_eff = -float('inf')
                max_work_eff_time = None
                max_EC = -float('inf')
                last_time = 0  # Initialize last_time
                x = 0

                try:
                    with open(file, 'r') as f:
                        lines = f.readlines()

                        for line in lines[23:]:  # Skip header
                            if "--- Compression shut down ---" in line:
                                break

                            pressure_bar_1 = float(line[27:42].strip()) if line[27:42].strip() else None

                            if pressure_bar_1 and pressure_bar_1 > max_pressure_1:
                                max_pressure_1 = pressure_bar_1

                        for line in lines[23:]:  # Skip header
                            if "--- Compression shut down ---" in line:
                                break

                            # Read values
                            time_in_seconds = float(line[0:12].strip()) if line[0:12].strip() else None
                            pressure_bar = float(line[27:42].strip()) if line[27:42].strip() else None
                            EC_val = float(line[227:257].strip()) if line[227:257].strip() else None
                            work_eff_val = float(line[297:317].strip()) if line[297:317].strip() else None
                            current_density = float(line[42:67].strip()) if line[42:67].strip() else None  # Current Density

                            # Save last time
                            if time_in_seconds:
                                last_time = time_in_seconds

                            # Find maximum values
                            if pressure_bar and pressure_bar > max_pressure:
                                max_pressure = pressure_bar
                                max_pressure_time = time_in_seconds
                                max_EC = EC_val  # Save EC at max pressure

                            if work_eff_val and work_eff_val > max_work_eff:
                                max_work_eff = work_eff_val
                                max_work_eff_time = time_in_seconds
                                eff_pressure = pressure_bar
                                eff_EC = EC_val
                                eff_current_density = current_density
                            
                            if pressure_bar and pressure_bar < (max_pressure_1 - 0.01*max_pressure_1) and x < 1 :
                                eq_time = time_in_seconds
                            else:
                                x = 2

                except Exception as e:
                    print(f"Error reading file {file}: {e}")

                filename = os.path.basename(file)
                filename_without_extension = os.path.splitext(filename)[0]
                result = "_".join(filename_without_extension.split('_')[4:])
                
                if max_pressure != -float('inf'):
                    if idx == 0:
                        latex_file.write(f"\\hline\n")
                        latex_file.write(f"\\multirow{{{num_files}}}{{*}}{{{x_value}}} & {result} & {last_time/3600:.2f} & {max_pressure:.2f} & {max_EC:.2f} & {max_pressure_time/3600:.2f} & {eq_time/3600:.2f} \\\\\n")
                    else:
                        latex_file.write(f"& {result} & {last_time/3600:.2f} & {max_pressure:.2f} & {max_EC:.2f} & {max_pressure_time/3600:.2f} & {eq_time/3600:.2f} \\\\\n")
                    if idx != num_files - 1:
                        latex_file.write("\\cline{2-7}\n")

        latex_file.write("\\hline \n")
        latex_file.write("\\end{longtable}\n")
        latex_file.write("This table presents measurements for different currents. For each measurement, it includes the duration and the maximum pressure reached. The consumption value at this maximum pressure and the time at which it occurred are also recorded. Additionally, the table indicates the time when the measurement reached equilibrium, defined as when the pressure was 99\% of the maximum value. \\ \n")
        latex_file.write("\\vspace{10mm}\n")

        # Second table
        latex_file.write("\\section*{Table 3: Efficiency and related data}\n")
        latex_file.write("\\vspace{5mm}\n")
        latex_file.write("\\setlength{\LTleft}{-2.25 cm} \n")
        latex_file.write("\\begin{longtable}{|c|c|c|c||c|c|c|c|} \n")
        latex_file.write("\\hline \n")
        latex_file.write("C. density & \multirow{2}{*}{Meas.} & Max. eff. & Eff. time & Pressure & Rel. pressure & Consumption & Mass  \\\ (A/cm$^{2}$) &  & \% & (h) & (bar) & \% & (kWh/kg) & (mg/(d·$cm^2$))  \\\\\n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endfirsthead \n")
        latex_file.write("\\hline \n")
        latex_file.write("C.density & \multirow{2}{*}{Meas.} & Max. eff. & Eff. time & Pressure & Rel. pressure & Consumption & Mass  \\\ (A/cm$^{2}$) &  & \% & (h) & (bar) & \% & (kWh/kg) & (mg/(d·$cm^2$))  \\\\\n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endhead \n")

        for group in output_data:
            x_value = group["x_value"]
            files = group["files"]
            num_files = len(files)

            latex_file.write("\\hline \n")

            for idx, file in enumerate(files):
                max_pressure = -float('inf')
                max_pressure_time = None
                max_work_eff = -float('inf')
                max_work_eff_time = None
                max_EC = -float('inf')
                last_time = 0  # Initialize last_time

                try:
                    with open(file, 'r') as f:
                        lines = f.readlines()
                        for line in lines[23:]:  # Skip header
                            if "--- Compression shut down ---" in line:
                                break

                            # Read values
                            time_in_seconds = float(line[0:12].strip()) if line[0:12].strip() else None
                            pressure_bar = float(line[27:42].strip()) if line[27:42].strip() else None
                            EC_val = float(line[227:257].strip()) if line[227:257].strip() else None
                            work_eff_val = float(line[297:317].strip()) if line[297:317].strip() else None
                            current_density = float(line[42:67].strip()) if line[42:67].strip() else None  # Current Density
                            net_flux_val = float(line[117:137].strip()) if line[117:137].strip() else None  # Net Flux

                            # Save last time
                            if time_in_seconds:
                                last_time = time_in_seconds

                            # Find maximum values
                            if pressure_bar and pressure_bar > max_pressure:
                                max_pressure = pressure_bar
                                max_pressure_time = time_in_seconds
                                max_EC = EC_val  # Save EC at max pressure

                            if work_eff_val and work_eff_val > max_work_eff:
                                max_work_eff = work_eff_val
                                max_work_eff_time = time_in_seconds
                                eff_pressure = pressure_bar
                                eff_EC = EC_val
                                eff_current_density = current_density
                                eff_net_flux = net_flux_val
                                eff_net_g = eff_net_flux*2.016*3600*24/5*1000 #mg/(day·cm^2)

                except Exception as e:
                    print(f"Error reading file {file}: {e}")

                filename = os.path.basename(file)
                filename_without_extension = os.path.splitext(filename)[0]
                result = "_".join(filename_without_extension.split('_')[4:])
                
                if max_work_eff != -float('inf'):
                    if idx == 0:
                        latex_file.write(f"\\hline\n")
                        latex_file.write(f"\\multirow{{{num_files}}}{{*}}{{{x_value}}} & {result} & {max_work_eff*100:.1f} & {max_work_eff_time/3600:.2f} & {eff_pressure:.2f} & {(eff_pressure)/(max_pressure)*100:.0f} & {eff_EC:.2f} & {eff_net_g:.2f} \\\\\n")
                    else:
                        latex_file.write(f"& {result} & {max_work_eff*100:.1f} & {max_work_eff_time/3600:.2f} & {eff_pressure:.2f} & {(eff_pressure)/(max_pressure)*100:.0f} & {eff_EC:.2f} & {eff_net_g:.2f}\\\\\n")
                    if idx != num_files - 1:
                        latex_file.write("\\cline{2-8}\n")

        latex_file.write("\\hline \n")
        latex_file.write("\\end{longtable}\n")
        latex_file.write("This table is based on the maximum overall efficiency value for each measurement. The time when this efficiency occurred was identified, and for this time, the following data is listed: pressure and its percentage in relation to the maximum pressure of the measurement (Rel. Pressure), consumption and mass generated for one day. \\ \n")
        latex_file.write("\\newpage \n")

    print(f"Tables added to LaTeX TXT file.")


def export_LaTeX_2(output_data, LATEX_FILE):
    """Adds a table for Vc and all DH and Pressure values to an existing LaTeX TXT file."""
    with open(LATEX_FILE, "a") as latex_file:

        # Start of the table
        latex_file.write("\\section*{Table 4: Volume and permeability values}\n")
        latex_file.write("\\vspace{5mm}\n")
        latex_file.write("\\setlength{\LTleft}{-3.5cm} \n")
        latex_file.write("\\begin{longtable}{|c|c|c|c|c|c|c|c|c|} \n")
        latex_file.write("\\hline \n")
        latex_file.write("C. density & \multirow{2}{*}{Meas.} & $V_c com$ & $V_c dif$ & $DH_m$ & $DH_{dep}$ & \multirow{2}{*}{Point} & $DH$ & Pressure \\\\ \n")
        latex_file.write("(A/cm$^{2}$) &  & (cm$^{3}$) & (cm$^{3}$) & (mol/Pa/m/s) & (mol/Pa/m/s) &  & (mol/Pa/m/s) & (Bar) \\\\ \n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endfirsthead \n")  # End of the first header
        latex_file.write("\\hline \n")
        latex_file.write("C. desnity & \multirow{2}{*}{Meas.} & $V_c com$ & $V_c dif$ & $DH_m$ & $DH_{dep}$ & \multirow{2}{*}{Point} & $DH$ & Pressure \\\\ \n")
        latex_file.write("(A/cm$^{2}$) &  & (cm$^{3}$) & (cm$^{3}$) & (mol/Pa/m/s) & (mol/Pa/m/s) &  & (mol/Pa/m/s) & (Bar) \\\\ \n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endhead \n")  # End of the header for the other rows
        
        for group in output_data:
            x_value = group["x_value"]
            files = group["files"]

            # Add a line above the current value
            latex_file.write("\\hline \n")

            num_folders = len(files)
            latex_file.write("\\hline\n")
            latex_file.write(f"\\multirow{{{num_folders}}}{{*}}{{{x_value}}}\n")

            for file in files:
                try:
                    with open(file, 'r') as f:
                        lines = f.readlines()

                        # Initialize values
                        Vc_value = "N/A"
                        volume_fit = "N/A"
                        DH_pressure_data = []

                        # Extract Vc
                        for i, line in enumerate(lines):
                            if 'Vc (cm3)' in line:
                                try:
                                    next_line = lines[i + 1].strip()  
                                    line_data = next_line.split()  
                                    Vc_value = float(line_data[3])  
                                except (ValueError, IndexError):
                                    Vc_value = "N/A"
                                
                        for line in lines:
                            if "Volume from exponential fit" in line:
                                try:
                                    volume_fit = float(line.split(":")[1].strip().split()[0])
                                except (ValueError, IndexError):
                                    volume_fit = "N/A"

                        for line in lines:
                            if "DH value from depression (mol/Pa/m/s)" in line:
                                try:
                                    DH_from_depression = float(line.split(":")[1].strip().split()[0])
                                except (ValueError, IndexError):
                                    DH_from_depression = "N/A"

                        # Extract DH and Pressure
                        DH_start = False
                        for line in lines:
                            parts = line.split()
                            if "Point" in line and "DH" in line and "Pressure" in line:
                                DH_start = True
                                continue
                            if DH_start and len(parts) == 3:
                                DH_pressure_data.append(parts)  # [Bod, DH, Pressure]

                        dh_mean_line = lines[18].strip()  # Odebíráme přebytečné mezery

                        # Regex pro extrakci hodnoty DH_mean a její chyby
                        dh_mean_pattern = r"DH mean:\s*([-+]?[0-9]*\.?[0-9]+e[-+]?[0-9]+)\s*\+\-\s*([-+]?[0-9]*\.?[0-9]+e[-+]?[0-9]+)"

                        # Hledání shody v konkrétním řádku
                        match = re.search(dh_mean_pattern, dh_mean_line)

                        if match:
                            # Extrahování hodnoty a chyby
                            DH_mean_value = float(match.group(1))
                            #print(f"DH_mean: {DH_mean_value}")
                        else:
                            print("No match in line:", dh_mean_line)


                        # Filename without path and extension
                        filename = os.path.basename(file)
                        filename_without_extension = os.path.splitext(filename)[0]
                        result = "_".join(filename_without_extension.split('_')[4:])
                        
                        # Number of rows for multirow
                        num_rows = len(DH_pressure_data)

                        # If there are DH and Pressure values
                        if num_rows > 0:
                            
                            latex_file.write(f"\\ & \\multirow{{{num_rows}}}{{*}}{{{result}}} & \\multirow{{{num_rows}}}{{*}}{{{Vc_value}}} & \\multirow{{{num_rows}}}{{*}}{{{volume_fit}}} & \\multirow{{{num_rows}}}{{*}}{{{DH_mean_value:.2e}}} & \\multirow{{{num_rows}}}{{*}}{{{DH_from_depression:.2e}}} \n")

                            for i, (point, dh_value, pressure) in enumerate(DH_pressure_data):
                                if "_" in point:
                                    point = point.replace("_", " ")

                                if i == 0:  # First row with data
                                    latex_file.write(f"& {point} & ${dh_value}$ & {pressure} \\\\\n")
                                    latex_file.write("\\cline{7-9} \n")
                                else:  # Other rows without repeating the headers
                                    latex_file.write(f"& & & & & & {point} & ${dh_value}$ & {pressure} \\\\\n")
                                    latex_file.write("\\cline{7-9} \n")
                            latex_file.write("\\cline{2-9}\n")
                        else:
                            latex_file.write(f"{x_value} & {result} & ${Vc_value}$ & N/A & N/A & N/A \\\\ \n")

                except Exception as e:
                    print(f"Error reading file {file}: {e}")

        # End of the table
        latex_file.write("\\hline \n\\end{longtable}\n")
        latex_file.write("This table contains values for the calculated volume from compression, but it also shows a volume from the diffusion. It also contains permeability values, which are obtained for the maximum achieved pressure and for three additional points from this point to the end of the measurement, with pressure at that point provided for comparison.\\ \n")

def export_LaTeX_3(output_data, LATEX_FILE):
    """Adds a table with average values for a current to an existing LaTeX TXT file."""

    with open(LATEX_FILE, "a") as latex_file:
        # Start of the table
        latex_file.write("\\section*{Table 1: Average values for a given current}\n")
        latex_file.write("\\vspace{5mm}\n")
        latex_file.write("\\setlength{\LTleft}{-4.5cm} \n")
        latex_file.write("\\begin{longtable}{|c|c|c|c|c|c|c|c|c|c|} \n")
        latex_file.write("\\hline \n")
        latex_file.write("C. desnity & Max. Pressure & Eq. time & Max. eff. & Eff. time & Consumption & $V_c com$ & $V_c dif$ & DH & $DH_{dep}$ \\\ (A/cm$^{2}$) & (bar) & (h) & (\%) & (h) & (kWh/kg) & (cm$^{3}$) & (cm$^{3}$) & (mol/Pa/m/s) & (mol/Pa/m/s) \\\ \n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endfirsthead \n")
        latex_file.write("\\hline \n")
        latex_file.write("C. density & Max. Pressure & Eq. time & Max. eff. & Eff. time & Consumption & $V_c com$ & $V_c dif$ & DH & $DH_{dep}$ \\\ (A/cm$^{2}$) & (bar) & (h) & (\%) & (h) & (kWh/kg) & (cm$^{3}$) & (cm$^{3}$) & (mol/Pa/m/s) & (mol/Pa/m/s) \\\ \n")
        latex_file.write("\\hline \n")
        latex_file.write("\\endhead \n")

        for group in output_data:
            x_value = group["x_value"]
            files = group["files"]

            # Summing values for average calculations
            total_pressure = 0
            total_EC_eff = 0
            total_work_eff = 0
            total_eq_time = 0
            total_work_eff_time = 0
            total_vc_value = 0
            total_vc_fit = 0
            total_DH = 0
            total_DH_depression = 0
            count = 0
            x = 0

            for file in files:
                max_pressure = -float('inf')
                max_pressure_1 = -float('inf')
                max_work_eff = -float('inf')
                max_work_eff_time = None
                max_EC_eff = -float('inf')

                try:
                    with open(file, 'r') as f:
                        lines = f.readlines()

                        for line in lines[23:]:  # Skip header
                            if "--- Compression shut down ---" in line:
                                break

                            pressure_bar_1 = float(line[27:42].strip()) if line[27:42].strip() else None

                            if pressure_bar_1 and pressure_bar_1 > max_pressure_1:
                                max_pressure_1 = pressure_bar_1


                        for line in lines[23:]:  # Skip header
                            if "--- Compression shut down ---" in line:
                                break

                            # Loading values
                            time_in_seconds = float(line[0:12].strip()) if line[0:12].strip() else None
                            pressure_bar = float(line[27:42].strip()) if line[27:42].strip() else None
                            EC_val = float(line[227:257].strip()) if line[227:257].strip() else None
                            work_eff_val = float(line[297:317].strip()) if line[297:317].strip() else None


                            # Searching for maximum values
                            if pressure_bar and pressure_bar > max_pressure:
                                max_pressure = pressure_bar
                                

                            if work_eff_val and work_eff_val > max_work_eff:
                                max_work_eff = work_eff_val
                                max_work_eff_time = time_in_seconds
                                max_EC_eff = EC_val  # Storing EC at max pressure

                            if pressure_bar and pressure_bar < (max_pressure_1 - 0.01*max_pressure_1) and x < 1:
                                eq_time = time_in_seconds
                            else:
                                x = 2

                        # Extracting Vc
                        for i, line in enumerate(lines):
                            if 'Vc (cm3)' in line:
                                try:
                                    next_line = lines[i + 1].strip()  
                                    line_data = next_line.split()  
                                    Vc_value = float(line_data[3])  
                                except (ValueError, IndexError):
                                    Vc_value = "N/A"
                                    
                        # Extracting Volume fit
                        for line in lines:
                            if "Volume from exponential fit" in line:
                                try:
                                    volume_fit = float(line.split(":")[1].strip().split()[0])
                                except (ValueError, IndexError):
                                    volume_fit = "N/A"
                        
                        for line in lines:
                            if "DH value from depression (mol/Pa/m/s)" in line:
                                try:
                                    DH_from_depression = float(line.split(":")[1].strip().split()[0])
                                except (ValueError, IndexError):
                                    DH_from_depression = "N/A"

                        dh_mean_line = lines[18].strip()  # Remove extra spaces

                        # Regex to extract DH_mean value and its error
                        dh_mean_pattern = r"DH mean:\s*([0-9e\.\+-]+)\s*\+\-\s*([0-9e\.\+-]+)"

                        # Search for a match in the specific line
                        match = re.search(dh_mean_pattern, dh_mean_line)

                        if match:
                            # Extract value and error
                            DH_mean_value = float(match.group(1))
                            #print(f"DH_mean: {DH_mean_value}")
                        else:
                            print("No match in line:", dh_mean_line)


                except Exception as e:
                    print(f"Error reading file {file}: {e}")

                if max_pressure != -float('inf'):
                    total_pressure += max_pressure
                    total_EC_eff += max_EC_eff
                    total_work_eff += max_work_eff * 100  # Efficiency in %
                    total_eq_time += eq_time / 3600  # Time to max pressure in hours
                    total_work_eff_time += max_work_eff_time / 3600  # Time to max efficiency in hours
                    total_vc_value += Vc_value
                    total_vc_fit += volume_fit
                    total_DH += DH_mean_value
                    total_DH_depression += DH_from_depression
                    count += 1

                    
            if count > 0:  # If there are values for the given current
                # Calculate averages
                avg_pressure = total_pressure / count
                avg_EC = total_EC_eff / count
                avg_work_eff = total_work_eff / count
                avg_pressure_time = total_eq_time / count
                avg_work_eff_time = total_work_eff_time / count
                avg_vc_value = total_vc_value / count
                avg_vc_fit = total_vc_fit / count
                avg_DH = total_DH / count
                avg_DH_depression = total_DH_depression / count
                
                # Add average values to the table
                latex_file.write(f"\\hline\n")
                latex_file.write(f"{x_value} & {avg_pressure:.2f} & {avg_pressure_time:.2f} & {avg_work_eff:.1f} & {avg_work_eff_time:.2f} & {avg_EC:.2f} & {avg_vc_value:.2f} & {avg_vc_fit:.2f} & {avg_DH:.2e} & {avg_DH_depression:.2e}\\\\ \n")

        latex_file.write("\\hline \n")
        latex_file.write("\\end{longtable}\n")
        latex_file.write("This table contains average values for the given current obtained from all measurements for that current. It includes maximum pressure, time to reach equilibrium (pressure corresponding to 99 \% of the maximum pressure), maximum efficiency (with the time to reach it), consumption at that time. At the end of the table are average values for calculated volume from the compression or diffusion and permeability.\\ \n")
